[package]
name = "azalea-viaversion"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
azalea = { version = "0.8.0", git = "https://github.com/azalea-rs/azalea" }
futures-util = "0.3.29"
indicatif = "0.17.7"
portpicker = "0.1.1"
reqwest = { version = "0.11.22", default-features = false, features = [
    "rustls-tls",
    "stream",
] }
tokio = { version = "1.34.0", features = ["process"] }
tracing = "0.1.40"
